name: trajectory
channels:
- defaults
- conda-forge
dependencies:
- python=3.6.5
- pip>=18.0
- conda>=4.5.9
- patchelf=0.9
- pip:
    - -f https://download.pytorch.org/whl/torch_stable.html
    - numpy==1.19.5
    - gym==0.18.0
    - mujoco-py==2.0.2.13
    - matplotlib==3.3.4
    - torch==1.7.1+cu101
    - torchvision==0.8.2+cu101
    - typed-argument-parser
    - git+https://github.com/JannerM/d4rl.git@d5719e2c6ef6ab3b1c678a846c02621abb8074a4
    - scikit-image==0.17.2
    - scikit-video==1.1.11
    - gitpython
